// <auto-generated />
namespace data_mos_ru.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _114 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_114));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180956125_114"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
