// <auto-generated />
namespace data_mos_ru.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _555 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_555));
        
        string IMigrationMetadata.Id
        {
            get { return "201906112020315_555"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
