// <auto-generated />
namespace data_mos_ru.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class org10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(org10));
        
        string IMigrationMetadata.Id
        {
            get { return "201906171309590_org10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
